create table if not exists public.transactions(user_id uuid not null references auth.users(id) on delete cascade,id text not null,date timestamptz not null default now(),customer text not null default 'Umum',name text not null default '',notes text not null default '',qty integer not null default 1,unit text not null default 'pcs',price numeric not null default 0,cost numeric not null default 0,created_at timestamptz not null default now(),primary key(user_id,id));
create table if not exists public.cash_flows(user_id uuid not null references auth.users(id) on delete cascade,id text not null,date timestamptz not null default now(),type text not null check(type in('in','out')),amount numeric not null default 0,notes text not null default '',created_at timestamptz not null default now(),primary key(user_id,id));
alter table public.transactions enable row level security;
alter table public.cash_flows enable row level security;
grant select,insert,update,delete on public.transactions to authenticated;
grant select,insert,update,delete on public.cash_flows to authenticated;
drop policy if exists transactions_own_rows on public.transactions;
create policy transactions_own_rows on public.transactions for all to authenticated using((select auth.uid())=user_id) with check((select auth.uid())=user_id);
drop policy if exists cash_flows_own_rows on public.cash_flows;
create policy cash_flows_own_rows on public.cash_flows for all to authenticated using((select auth.uid())=user_id) with check((select auth.uid())=user_id);